### ISSUE TITLE
10.14.4的版本需要更换无线网卡和三键触摸吗？

### ISSUE THREAD

**Issue by josangmi** [coderzhouyu/mac#1]
10.14.4的版本需要更换无线网卡和三键触摸吗？ 还有那些不完美的地方？ 睡眠好用了吗？ 谢谢

**Comment by coderzhouyu** [comment]
额 无线网卡要刷白名单没折腾买了个外置的，三键触摸应该是有的，睡眠偶尔会睡死。不完美的话开机时会有一次花屏，各种补丁也没修复，别的也没发现。
